{% set name = "poissonrecon" %}
{% set version = "v10.04" %}
{% set commit = "ff275f3a71d5d8017467008ad15075af328fb1e8" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/mkazhdan/PoissonRecon/archive/{{ commit }}.tar.gz
  sha256: af6d034db7f6adab322237f2a241f4c3707c4ccb93c459f45a9009963d08a82f

build:
    number: 0

# requirements:
  # build:
    # - {{ compiler("c") }}
    # - {{ compiler("cxx") }}

test:
  commands:
    - PoissonRecon --help

about:
  home: http://www.cs.jhu.edu/~misha
  license: MIT
  summary: Poisson Surface Reconstruction

extra:
  recipe-maintainers:
    - v-turin
